### ISSUE TITLE
We need API reference documentation for GXC API

### ISSUE THREAD

**Issue by jacquesbeaurain** [GeosoftInc/gxc#5]

**Comment by ianneilmacleod** [comment]
@jbgeosoft I'm ok that GXC developers simply refer to the .gxh files.  But in the interest of completeness an automated API doc would be nice.

**Comment by ianneilmacleod** [comment]
When resolved change the API Reference link on: https://geosoftgxdev.atlassian.net/wiki/spaces/GD/pages/44367898/Release+Version+Table
